

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Purchase : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Purchase entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Purchase()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Purchase(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Purchase> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Purchase.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Purchase_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Purchase_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Purchase.DetailsClass.SetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime PurchaseDate
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchaseDate);
            }
            set
            {
                global::LightSwitchApplication.Purchase.DetailsClass.SetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchaseDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PurchaseDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BookNo
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.BookNo);
            }
            set
            {
                global::LightSwitchApplication.Purchase.DetailsClass.SetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.BookNo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookNo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookNo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookNo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DriverName
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.DriverName);
            }
            set
            {
                global::LightSwitchApplication.Purchase.DetailsClass.SetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.DriverName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DriverName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DriverName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DriverName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string VehicleNo
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.VehicleNo);
            }
            set
            {
                global::LightSwitchApplication.Purchase.DetailsClass.SetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.VehicleNo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VehicleNo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VehicleNo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VehicleNo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double TotalAmount
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.TotalAmount);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalAmount_Compute(ref double result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TotalAmount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double PaidAmount
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PaidAmount);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PaidAmount_Compute(ref double result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PaidAmount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double DueAmount
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.DueAmount);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DueAmount_Compute(ref double result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DueAmount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Status
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Status);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Status_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Purchase.DetailsClass.SetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Company Company
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Company);
            }
            set
            {
                global::LightSwitchApplication.Purchase.DetailsClass.SetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Company, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PurchaseItem> PurchaseItems
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchaseItems);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PurchaseItem> PurchaseItemsQuery
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetQuery(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchaseItems);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PurchasePayment> PurchasePayments
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetValue(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchasePayments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PurchasePayment> PurchasePaymentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Purchase.DetailsClass.GetQuery(this, global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchasePayments);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Purchase,
                global::LightSwitchApplication.Purchase.DetailsClass,
                global::LightSwitchApplication.Purchase.DetailsClass.IImplementation,
                global::LightSwitchApplication.Purchase.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass>.Entry
                __PurchaseEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass>.Entry(
                    global::LightSwitchApplication.Purchase.DetailsClass.__Purchase_CreateNew,
                    global::LightSwitchApplication.Purchase.DetailsClass.__Purchase_Created,
                    global::LightSwitchApplication.Purchase.DetailsClass.__Purchase_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Purchase __Purchase_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Purchase> es)
            {
                return new global::LightSwitchApplication.Purchase(es);
            }
            private static void __Purchase_Created(global::LightSwitchApplication.Purchase e)
            {
                e.Purchase_Created();
            }
            private static bool __Purchase_AllowSaveWithErrors(global::LightSwitchApplication.Purchase e)
            {
                bool result = false;
                e.Purchase_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Purchase.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.DateTime> PurchaseDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchaseDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string> BookNo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.BookNo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string> DriverName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.DriverName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string> VehicleNo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.VehicleNo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double> TotalAmount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.TotalAmount) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double> PaidAmount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PaidAmount) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double> DueAmount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.DueAmount) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string> Status
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Status) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.Company> Company
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Company) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchaseItem> PurchaseItems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchaseItems) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchaseItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchasePayment> PurchasePayments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchasePayments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchasePayment>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime PurchaseDate { get; set; }
                new string BookNo { get; set; }
                new string DriverName { get; set; }
                new string VehicleNo { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Company { get; set; }
                new global::System.Collections.IEnumerable PurchaseItems { get; }
                new global::System.Collections.IEnumerable PurchasePayments { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, int>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.DateTime>.Entry
                    PurchaseDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.DateTime>.Entry(
                        "PurchaseDate",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseDate_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseDate_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseDate_GetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseDate_SetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseDate_OnValueChanged);
                private static void _PurchaseDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._PurchaseDate, sf);
                }
                private static bool _PurchaseDate_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.PurchaseDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _PurchaseDate_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PurchaseDate_Validate(r);
                }
                private static global::System.DateTime _PurchaseDate_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.PurchaseDate;
                }
                private static void _PurchaseDate_SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.PurchaseDate = global::LightSwitchApplication.Purchase.DetailsClass.TruncateDate(v);
                }
                private static void _PurchaseDate_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.PurchaseDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry
                    BookNo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry(
                        "BookNo",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._BookNo_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._BookNo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._BookNo_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._BookNo_GetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._BookNo_SetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._BookNo_OnValueChanged);
                private static void _BookNo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._BookNo, sf);
                }
                private static bool _BookNo_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.BookNo_IsReadOnly(ref result);
                    return result;
                }
                private static void _BookNo_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.BookNo_Validate(r);
                }
                private static string _BookNo_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.BookNo;
                }
                private static void _BookNo_SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d, string v)
                {
                    d.ImplementationEntity.BookNo = v;
                }
                private static void _BookNo_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.BookNo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry
                    DriverName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry(
                        "DriverName",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DriverName_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DriverName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DriverName_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DriverName_GetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DriverName_SetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DriverName_OnValueChanged);
                private static void _DriverName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._DriverName, sf);
                }
                private static bool _DriverName_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.DriverName_IsReadOnly(ref result);
                    return result;
                }
                private static void _DriverName_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DriverName_Validate(r);
                }
                private static string _DriverName_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.DriverName;
                }
                private static void _DriverName_SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DriverName = v;
                }
                private static void _DriverName_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.DriverName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry
                    VehicleNo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry(
                        "VehicleNo",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._VehicleNo_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._VehicleNo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._VehicleNo_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._VehicleNo_GetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._VehicleNo_SetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._VehicleNo_OnValueChanged);
                private static void _VehicleNo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._VehicleNo, sf);
                }
                private static bool _VehicleNo_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.VehicleNo_IsReadOnly(ref result);
                    return result;
                }
                private static void _VehicleNo_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.VehicleNo_Validate(r);
                }
                private static string _VehicleNo_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.VehicleNo;
                }
                private static void _VehicleNo_SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d, string v)
                {
                    d.ImplementationEntity.VehicleNo = v;
                }
                private static void _VehicleNo_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.VehicleNo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Entry
                    TotalAmount = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Entry(
                        "TotalAmount",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._TotalAmount_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._TotalAmount_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._TotalAmount_ComputeValue);
                private static void _TotalAmount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._TotalAmount, sf);
                }
                private static void _TotalAmount_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TotalAmount_Validate(r);
                }
                private static double _TotalAmount_ComputeValue(global::LightSwitchApplication.Purchase e)
                {
                    double value = default(double);
                    e.TotalAmount_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Entry
                    PaidAmount = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Entry(
                        "PaidAmount",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PaidAmount_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PaidAmount_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PaidAmount_ComputeValue);
                private static void _PaidAmount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._PaidAmount, sf);
                }
                private static void _PaidAmount_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PaidAmount_Validate(r);
                }
                private static double _PaidAmount_ComputeValue(global::LightSwitchApplication.Purchase e)
                {
                    double value = default(double);
                    e.PaidAmount_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Entry
                    DueAmount = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Entry(
                        "DueAmount",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DueAmount_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DueAmount_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._DueAmount_ComputeValue);
                private static void _DueAmount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._DueAmount, sf);
                }
                private static void _DueAmount_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DueAmount_Validate(r);
                }
                private static double _DueAmount_ComputeValue(global::LightSwitchApplication.Purchase e)
                {
                    double value = default(double);
                    e.DueAmount_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry
                    Status = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry(
                        "Status",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Status_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Status_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Status_ComputeValue);
                private static void _Status_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._Status, sf);
                }
                private static void _Status_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Status_Validate(r);
                }
                private static string _Status_ComputeValue(global::LightSwitchApplication.Purchase e)
                {
                    string value = default(string);
                    e.Status_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Company = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Company",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_ComputeIsReadOnly,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_Validate,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_GetCoreImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_GetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_SetImplementationValue,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_Refresh,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._Company_OnValueChanged);
                private static void _Company_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._Company, sf);
                }
                private static bool _Company_ComputeIsReadOnly(global::LightSwitchApplication.Purchase e)
                {
                    bool result = false;
                    e.Company_IsReadOnly(ref result);
                    return result;
                }
                private static void _Company_Validate(global::LightSwitchApplication.Purchase e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Company_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Company_GetCoreImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.Company;
                }
                private static global::LightSwitchApplication.Company _Company_GetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Company, ref d._Company);
                }
                private static void _Company_SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass d, global::LightSwitchApplication.Company v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Company, ref d._Company, (i, ev) => i.Company = ev, v);
                }
                private static void _Company_Refresh(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.Company, ref d._Company);
                }
                private static void _Company_OnValueChanged(global::LightSwitchApplication.Purchase e)
                {
                    e.Company_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchaseItem>.Entry
                    PurchaseItems = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchaseItem>.Entry(
                        "PurchaseItems",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseItems_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseItems_GetReferencedEntities,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchaseItems_GetEntityCollection);
                private static void _PurchaseItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchaseItem>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._PurchaseItems, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PurchaseItem> _PurchaseItems_GetReferencedEntities(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PurchaseItem, global::LightSwitchApplication.PurchaseItem.DetailsClass>(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchaseItems, ref d._PurchaseItems);
                }
                private static global::System.Collections.IEnumerable _PurchaseItems_GetEntityCollection(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.PurchaseItems;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchasePayment>.Entry
                    PurchasePayments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchasePayment>.Entry(
                        "PurchasePayments",
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchasePayments_Stub,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchasePayments_GetReferencedEntities,
                        global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties._PurchasePayments_GetEntityCollection);
                private static void _PurchasePayments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Purchase.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchasePayment>.Data> c, global::LightSwitchApplication.Purchase.DetailsClass d, object sf)
                {
                    c(d, ref d._PurchasePayments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PurchasePayment> _PurchasePayments_GetReferencedEntities(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PurchasePayment, global::LightSwitchApplication.PurchasePayment.DetailsClass>(global::LightSwitchApplication.Purchase.DetailsClass.PropertySetProperties.PurchasePayments, ref d._PurchasePayments);
                }
                private static global::System.Collections.IEnumerable _PurchasePayments_GetEntityCollection(global::LightSwitchApplication.Purchase.DetailsClass d)
                {
                    return d.ImplementationEntity.PurchasePayments;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.DateTime>.Data _PurchaseDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data _BookNo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data _DriverName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data _VehicleNo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Data _TotalAmount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Data _PaidAmount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, double>.Data _DueAmount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data _Status;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.Company>.Data _Company;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchaseItem>.Data _PurchaseItems;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Purchase, global::LightSwitchApplication.Purchase.DetailsClass, global::LightSwitchApplication.PurchasePayment>.Data _PurchasePayments;
            
        }
    
        #endregion
    }
    
    #endregion
}
